### array的含义是多维数组
* 运算法则是一对一的运算，并非矩阵运算

In [1]:
import numpy as np
data1 = [range(1,10),range(11,20)]

arr1 = np.array(data1)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [2]:
arr2 = np.ones((2,9))
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [3]:
# 数组之间可以加减乘除，或许可以有更多的运算。运算法则是一对一的运算，并非矩阵运算
arr1+arr2

array([[ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20.]])

### zeros ones empty eye 使用

In [4]:
np.zeros((3,2)) # 全是0的array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
np.ones((3,2)) # 全是1的array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.empty((3,2)) # 全是垃圾值的array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.eye(3)      # 对角线全是1的array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 随机生成一个n*n的数组（array）

In [8]:
np.random.randn(4,4)

array([[ 0.76406648,  1.75642098,  0.02753784,  0.62597014],
       [-0.05333315,  0.85645906,  1.22973287, -0.32768415],
       [ 1.77444324, -0.34087871,  0.36790359,  0.06367917],
       [-1.08593764,  0.57909244,  0.62262425, -1.9092757 ]])

### 修改数组的数据类型

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1 = arr1.astype("float64") # 修改数据类型
arr1.dtype

dtype('float64')

### 数组和标量之间的运算

In [11]:
arr1

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19.]])

In [12]:
np.power(arr1,2)

array([[  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81.],
       [121., 144., 169., 196., 225., 256., 289., 324., 361.]])

### 数组的切片运算符

In [13]:
arr2 = np.arange(1,9)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
s=arr2[2:5]
s

array([3, 4, 5])

In [15]:
s2=arr2[2:5].copy()
s2

array([3, 4, 5])

### 布尔索引
* 不支持python内置的 and or等
* 支持 & | numpy自带的运算符

In [16]:
arr1 = [0,0,1,0,1,0,1]
arr1 = np.array(arr1)

In [17]:
# 输出arr1中是1的布尔值
arr1 == 1

array([False, False,  True, False,  True, False,  True])

In [18]:
arr1[arr1==1]

array([1, 1, 1])

### 数组转置

In [19]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
# 对数组转置 类似矩阵转置
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### np.where(con, x, y)
就是相当于 [x if con else y] 如果con为真选取x，否则选取y

In [21]:
x = arr1[0][:]
x

array([1, 2, 3])

In [22]:
y = arr1[2][:]
y

array([7, 8, 9])

In [23]:
con = [False, True, False]
con

[False, True, False]

In [24]:
print(x, "\n", y, "\n", con)

[1 2 3] 
 [7 8 9] 
 [False, True, False]


In [25]:
np.where(con, x,y)

array([7, 2, 9])

### 矩阵运算
* 务必记得转成 mat

In [26]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
mArr1=np.mat(arr1)
mArr1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [28]:
v = np.mat(arr1[0])
v = v.T
v

matrix([[1],
        [2],
        [3]])

In [29]:
# 矩阵相乘
mArr1*v

matrix([[14],
        [32],
        [50]])